// Generated by Sterling SDK Generator — test suite
// Orchestrator Control Plane API v0.1.0

//! Integration-style tests for the generated client.
//! Each test spins up a lightweight HTTP server to capture the request.

use vers-sdk::client::Client;
use std::sync::{Arc, Mutex};
use std::io::{Read, Write};
use std::net::TcpListener;

/// Captured HTTP request info.
#[derive(Debug, Clone, Default)]
struct CapturedRequest {
    method: String,
    path: String,
    body: String,
}

/// Start a simple single-request HTTP server that responds with 200 OK.
/// Returns (addr, captured) so tests can inspect what was received.
fn mock_server() -> (String, Arc<Mutex<CapturedRequest>>) {
    let listener = TcpListener::bind("127.0.0.1:0").expect("bind");
    let addr = format!("http://{}", listener.local_addr().unwrap());
    let cap = Arc::new(Mutex::new(CapturedRequest::default()));
    let cap2 = Arc::clone(&cap);
    std::thread::spawn(move || {
        // Accept one connection
        if let Ok((mut stream, _)) = listener.accept() {
            let mut buf = [0u8; 4096];
            let n = stream.read(&mut buf).unwrap_or(0);
            let raw = String::from_utf8_lossy(&buf[..n]).to_string();
            // Parse first line: "METHOD /path HTTP/1.1"
            if let Some(first_line) = raw.lines().next() {
                let parts: Vec<&str> = first_line.split_whitespace().collect();
                if parts.len() >= 2 {
                    let mut c = cap2.lock().unwrap();
                    c.method = parts[0].to_string();
                    c.path = parts[1].to_string();
                }
            }
            // Extract body (after \r\n\r\n)
            if let Some(idx) = raw.find("\r\n\r\n") {
                let mut c = cap2.lock().unwrap();
                c.body = raw[idx + 4..].to_string();
            }
            let response = "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: 2\r\n\r\n{}";
            let _ = stream.write_all(response.as_bytes());
        }
    });
    // Small delay to let the server thread start
    std::thread::sleep(std::time::Duration::from_millis(50));
    (addr, cap)
}

/// Start a mock server that returns a specific status code.
fn mock_error_server(status: u16) -> String {
    let listener = TcpListener::bind("127.0.0.1:0").expect("bind");
    let addr = format!("http://{}", listener.local_addr().unwrap());
    std::thread::spawn(move || {
        if let Ok((mut stream, _)) = listener.accept() {
            let mut buf = [0u8; 4096];
            let _ = stream.read(&mut buf);
            let body = r#"{"message":"error"}"#;
            let resp = format!(
                "HTTP/1.1 {} Error\r\nContent-Type: application/json\r\nContent-Length: {}\r\n\r\n{}",
                status,
                body.len(),
                body
            );
            let _ = stream.write_all(resp.as_bytes());
        }
    });
    std::thread::sleep(std::time::Duration::from_millis(50));
    addr
}

#[tokio::test]
async fn test_vm_status() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.vm_status("test-id", None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "GET", "vm_status should use GET");
    assert!(c.path.starts_with("/"), "vm_status path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_resize_vm_disk() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.resize_vm_disk("test-id", &serde_json::json!({}), None, None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "PATCH", "resize_vm_disk should use PATCH");
    assert!(c.path.starts_with("/"), "resize_vm_disk path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_exec_vm_stream_attach() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.exec_vm_stream_attach("test-id", &serde_json::json!({}), None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "POST", "exec_vm_stream_attach should use POST");
    assert!(c.path.starts_with("/"), "exec_vm_stream_attach path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_list_vms() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.list_vms(None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "GET", "list_vms should use GET");
    assert!(c.path.starts_with("/"), "list_vms path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_create_new_root_vm() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.create_new_root_vm(&serde_json::json!({}), None, None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "POST", "create_new_root_vm should use POST");
    assert!(c.path.starts_with("/"), "create_new_root_vm path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_vm_logs() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.vm_logs("test-id", None, None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "GET", "vm_logs should use GET");
    assert!(c.path.starts_with("/"), "vm_logs path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_branch_by_ref() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.branch_by_ref("test-id", "test-id", &serde_json::json!({}), None, None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "POST", "branch_by_ref should use POST");
    assert!(c.path.starts_with("/"), "branch_by_ref path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_label_vm() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.label_vm("test-id", &serde_json::json!({}), None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "PATCH", "label_vm should use PATCH");
    assert!(c.path.starts_with("/"), "label_vm path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_list_public_commits() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.list_public_commits(None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "GET", "list_public_commits should use GET");
    assert!(c.path.starts_with("/"), "list_public_commits path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_get_image_status() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.get_image_status("test-id", None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "GET", "get_image_status should use GET");
    assert!(c.path.starts_with("/"), "get_image_status path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_list_public_repo_tags() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.list_public_repo_tags("test-id", "test-id", None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "GET", "list_public_repo_tags should use GET");
    assert!(c.path.starts_with("/"), "list_public_repo_tags path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_version_handler() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.version_handler(None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "GET", "version_handler should use GET");
    assert!(c.path.starts_with("/"), "version_handler path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_branch_by_tag() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.branch_by_tag("test-id", &serde_json::json!({}), None, None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "POST", "branch_by_tag should use POST");
    assert!(c.path.starts_with("/"), "branch_by_tag path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_get_repo_tag() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.get_repo_tag("test-id", "test-id", None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "GET", "get_repo_tag should use GET");
    assert!(c.path.starts_with("/"), "get_repo_tag path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_delete_repo_tag() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.delete_repo_tag("test-id", "test-id", None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "DELETE", "delete_repo_tag should use DELETE");
    assert!(c.path.starts_with("/"), "delete_repo_tag path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_update_repo_tag() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.update_repo_tag("test-id", "test-id", &serde_json::json!({}), None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "PATCH", "update_repo_tag should use PATCH");
    assert!(c.path.starts_with("/"), "update_repo_tag path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_branch_vm() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.branch_vm("test-id", &serde_json::json!({}), None, None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "POST", "branch_vm should use POST");
    assert!(c.path.starts_with("/"), "branch_vm path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_get_repository() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.get_repository("test-id", None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "GET", "get_repository should use GET");
    assert!(c.path.starts_with("/"), "get_repository path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_delete_repository() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.delete_repository("test-id", None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "DELETE", "delete_repository should use DELETE");
    assert!(c.path.starts_with("/"), "delete_repository path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_list_parent_commits() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.list_parent_commits("test-id", None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "GET", "list_parent_commits should use GET");
    assert!(c.path.starts_with("/"), "list_parent_commits path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_validate_key() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.validate_key(&serde_json::json!({}), None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "POST", "validate_key should use POST");
    assert!(c.path.starts_with("/"), "validate_key path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_fork_repository() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.fork_repository(&serde_json::json!({}), None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "POST", "fork_repository should use POST");
    assert!(c.path.starts_with("/"), "fork_repository path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_list_repositories() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.list_repositories(None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "GET", "list_repositories should use GET");
    assert!(c.path.starts_with("/"), "list_repositories path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_create_repository() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.create_repository(&serde_json::json!({}), None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "POST", "create_repository should use POST");
    assert!(c.path.starts_with("/"), "create_repository path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_update_vm_state() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.update_vm_state("test-id", &serde_json::json!({}), None, None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "PATCH", "update_vm_state should use PATCH");
    assert!(c.path.starts_with("/"), "update_vm_state path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_create_image() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.create_image(&serde_json::json!({}), None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "POST", "create_image should use POST");
    assert!(c.path.starts_with("/"), "create_image path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_restore_from_commit() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.restore_from_commit(&serde_json::json!({}), None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "POST", "restore_from_commit should use POST");
    assert!(c.path.starts_with("/"), "restore_from_commit path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_get_domain() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.get_domain("test-id", None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "GET", "get_domain should use GET");
    assert!(c.path.starts_with("/"), "get_domain path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_delete_domain() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.delete_domain("test-id", None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "DELETE", "delete_domain should use DELETE");
    assert!(c.path.starts_with("/"), "delete_domain path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_list_tags() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.list_tags(None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "GET", "list_tags should use GET");
    assert!(c.path.starts_with("/"), "list_tags path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_create_tag() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.create_tag(&serde_json::json!({}), None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "POST", "create_tag should use POST");
    assert!(c.path.starts_with("/"), "create_tag path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_list_public_repositories() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.list_public_repositories(None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "GET", "list_public_repositories should use GET");
    assert!(c.path.starts_with("/"), "list_public_repositories path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_get_public_repo_tag() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.get_public_repo_tag("test-id", "test-id", "test-id", None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "GET", "get_public_repo_tag should use GET");
    assert!(c.path.starts_with("/"), "get_public_repo_tag path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_get_vm_metadata() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.get_vm_metadata("test-id", None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "GET", "get_vm_metadata should use GET");
    assert!(c.path.starts_with("/"), "get_vm_metadata path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_list_env_vars() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.list_env_vars(None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "GET", "list_env_vars should use GET");
    assert!(c.path.starts_with("/"), "list_env_vars path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_set_env_vars() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.set_env_vars(&serde_json::json!({}), None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "PUT", "set_env_vars should use PUT");
    assert!(c.path.starts_with("/"), "set_env_vars path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_delete_vm() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.delete_vm("test-id", None, None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "DELETE", "delete_vm should use DELETE");
    assert!(c.path.starts_with("/"), "delete_vm path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_list_commits() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.list_commits(None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "GET", "list_commits should use GET");
    assert!(c.path.starts_with("/"), "list_commits path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_get_tag() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.get_tag("test-id", None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "GET", "get_tag should use GET");
    assert!(c.path.starts_with("/"), "get_tag path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_delete_tag() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.delete_tag("test-id", None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "DELETE", "delete_tag should use DELETE");
    assert!(c.path.starts_with("/"), "delete_tag path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_update_tag() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.update_tag("test-id", &serde_json::json!({}), None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "PATCH", "update_tag should use PATCH");
    assert!(c.path.starts_with("/"), "update_tag path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_branch_by_vm() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.branch_by_vm("test-id", &serde_json::json!({}), None, None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "POST", "branch_by_vm should use POST");
    assert!(c.path.starts_with("/"), "branch_by_vm path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_delete_env_var() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.delete_env_var("test-id", None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "DELETE", "delete_env_var should use DELETE");
    assert!(c.path.starts_with("/"), "delete_env_var path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_delete_image() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.delete_image("test-id", None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "DELETE", "delete_image should use DELETE");
    assert!(c.path.starts_with("/"), "delete_image path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_commit_vm() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.commit_vm("test-id", &serde_json::json!({}), None, None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "POST", "commit_vm should use POST");
    assert!(c.path.starts_with("/"), "commit_vm path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_delete_commit() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.delete_commit("test-id", None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "DELETE", "delete_commit should use DELETE");
    assert!(c.path.starts_with("/"), "delete_commit path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_update_commit() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.update_commit("test-id", &serde_json::json!({}), None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "PATCH", "update_commit should use PATCH");
    assert!(c.path.starts_with("/"), "update_commit path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_list_repo_tags() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.list_repo_tags("test-id", None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "GET", "list_repo_tags should use GET");
    assert!(c.path.starts_with("/"), "list_repo_tags path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_create_repo_tag() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.create_repo_tag("test-id", &serde_json::json!({}), None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "POST", "create_repo_tag should use POST");
    assert!(c.path.starts_with("/"), "create_repo_tag path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_deploy_handler() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.deploy_handler(&serde_json::json!({}), None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "POST", "deploy_handler should use POST");
    assert!(c.path.starts_with("/"), "deploy_handler path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_exec_vm() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.exec_vm("test-id", &serde_json::json!({}), None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "POST", "exec_vm should use POST");
    assert!(c.path.starts_with("/"), "exec_vm path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_set_repository_visibility() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.set_repository_visibility("test-id", &serde_json::json!({}), None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "PATCH", "set_repository_visibility should use PATCH");
    assert!(c.path.starts_with("/"), "set_repository_visibility path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_exec_vm_stream() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.exec_vm_stream("test-id", &serde_json::json!({}), None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "POST", "exec_vm_stream should use POST");
    assert!(c.path.starts_with("/"), "exec_vm_stream path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_list_domains() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.list_domains(None, None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "GET", "list_domains should use GET");
    assert!(c.path.starts_with("/"), "list_domains path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_create_domain() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.create_domain(&serde_json::json!({}), None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "POST", "create_domain should use POST");
    assert!(c.path.starts_with("/"), "create_domain path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_ssh_key() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.ssh_key("test-id", None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "GET", "ssh_key should use GET");
    assert!(c.path.starts_with("/"), "ssh_key path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_list_images() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.list_images(None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "GET", "list_images should use GET");
    assert!(c.path.starts_with("/"), "list_images path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_read_file_vm() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.read_file_vm("test-id", None, None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "GET", "read_file_vm should use GET");
    assert!(c.path.starts_with("/"), "read_file_vm path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_write_file_vm() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.write_file_vm("test-id", &serde_json::json!({}), None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "PUT", "write_file_vm should use PUT");
    assert!(c.path.starts_with("/"), "write_file_vm path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_upload_image() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.upload_image(&serde_json::json!({}), None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "POST", "upload_image should use POST");
    assert!(c.path.starts_with("/"), "upload_image path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_get_public_repository() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.get_public_repository("test-id", "test-id", None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "GET", "get_public_repository should use GET");
    assert!(c.path.starts_with("/"), "get_public_repository path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_branch_by_commit() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.branch_by_commit("test-id", &serde_json::json!({}), None, None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "POST", "branch_by_commit should use POST");
    assert!(c.path.starts_with("/"), "branch_by_commit path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_error_non_2xx() {
    // Verify that non-2xx responses result in errors
    let addr = mock_error_server(400);
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let result = client.vm_status("test-id", None).await;
    // The reqwest-based client may or may not surface this as an error
    // depending on whether the operation deserializes the response.
    // At minimum the request should complete without panic.
    drop(result);
}
