// Generated by Sterling SDK Generator
// Orchestrator Control Plane API v0.1.0

use serde::{Deserialize, Serialize};

/// Response body for GET /env_vars and PUT /env_vars.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EnvVarsResponse {
    /// All environment variables currently set for the authenticated user.
    #[serde(rename = "vars")]
    pub vars: serde_json::Value,
}

/// Response body for POST /api/v1/repositories
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateRepositoryResponse {
    /// The name of the repository
    #[serde(rename = "name")]
    pub name: String,
    /// The ID of the newly created repository
    #[serde(rename = "repo_id")]
    pub repo_id: String,
}

/// Public repository information (includes owner org name for namespacing)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PublicRepositoryInfo {
    /// When the repository was created
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Optional description
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "description")]
    pub description: Option<serde_json::Value>,
    /// Full reference: org_name/repo_name
    #[serde(rename = "full_name")]
    pub full_name: String,
    /// The repository name
    #[serde(rename = "name")]
    pub name: String,
    /// The owning organization's name (namespace)
    #[serde(rename = "org_name")]
    pub org_name: String,
    /// The repository's unique identifier
    #[serde(rename = "repo_id")]
    pub repo_id: String,
}

/// Response body for GET /api/v1/commit_tags
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ListTagsResponse {
    /// List of all tags in the user's organization
    #[serde(rename = "tags")]
    pub tags: Vec<TagInfo>,
}

/// Request body for creating a tag within a repository: POST /api/v1/repositories/{repo_name}/tags
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateRepoTagRequest {
    /// The commit ID this tag should point to
    #[serde(rename = "commit_id")]
    pub commit_id: String,
    /// Optional description of what this tag represents
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "description")]
    pub description: Option<serde_json::Value>,
    /// The tag name (e.g. 'latest', 'v1.0')
    #[serde(rename = "tag_name")]
    pub tag_name: String,
}

/// Response struct for GET api/v1/system/version
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrchestratorVersion {
    /// Executable identifier; should be 'orchestrator'
    #[serde(rename = "executable_name")]
    pub executable_name: String,
    /// Current git hash used for the build
    #[serde(rename = "git_hash")]
    pub git_hash: String,
    /// Current workspace version
    #[serde(rename = "workspace_version")]
    pub workspace_version: String,
}

/// 
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ListCommitsResponse {
    #[serde(rename = "commits")]
    pub commits: Vec<CommitInfo>,
    #[serde(rename = "limit")]
    pub limit: i64,
    #[serde(rename = "offset")]
    pub offset: i64,
    #[serde(rename = "total")]
    pub total: i64,
}

/// Response body for `POST /api/v1/deploy`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeployResponse {
    #[serde(rename = "project_id")]
    pub project_id: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "vm_id")]
    pub vm_id: String,
}

/// Response body for GET /api/v1/repositories/{repo_name}/tags
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ListRepoTagsResponse {
    /// The repository name
    #[serde(rename = "repository")]
    pub repository: String,
    /// List of tags in this repository
    #[serde(rename = "tags")]
    pub tags: Vec<RepoTagInfo>,
}

/// 
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BaseImageInfo {
    #[serde(rename = "base_image_id")]
    pub base_image_id: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "description")]
    pub description: Option<serde_json::Value>,
    #[serde(rename = "image_name")]
    pub image_name: String,
    #[serde(rename = "is_public")]
    pub is_public: bool,
    #[serde(rename = "owner_id")]
    pub owner_id: String,
    #[serde(rename = "size_mib")]
    pub size_mib: i32,
    #[serde(rename = "source_type")]
    pub source_type: String,
}

/// Response body for POST /api/vm/{vm_id}/exec
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VmExecResponse {
    /// Exec identifier associated with this run.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "exec_id")]
    pub exec_id: Option<serde_json::Value>,
    /// Exit code returned by the command.
    #[serde(rename = "exit_code")]
    pub exit_code: i32,
    /// UTF-8 decoded stderr (lossy).
    #[serde(rename = "stderr")]
    pub stderr: String,
    /// UTF-8 decoded stdout (lossy).
    #[serde(rename = "stdout")]
    pub stdout: String,
}

/// 
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateBaseImageResponse {
    #[serde(rename = "image_name")]
    pub image_name: String,
    #[serde(rename = "job_id")]
    pub job_id: String,
    #[serde(rename = "status")]
    pub status: String,
}

/// Request body for POST /api/vm/{vm_id}/exec
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VmExecRequest {
    /// Command and arguments to execute.
    #[serde(rename = "command")]
    pub command: Vec<String>,
    /// Optional environment variables to set for the process.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "env")]
    pub env: Option<serde_json::Value>,
    /// Optional exec identifier for tracking.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "exec_id")]
    pub exec_id: Option<serde_json::Value>,
    /// Optional stdin payload passed to the command.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "stdin")]
    pub stdin: Option<serde_json::Value>,
    /// Timeout in seconds (0 = no timeout).
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "timeout_secs")]
    pub timeout_secs: Option<serde_json::Value>,
    /// Optional working directory for the command.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "working_dir")]
    pub working_dir: Option<serde_json::Value>,
}

/// 
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NewVmsResponse {
    #[serde(rename = "vms")]
    pub vms: Vec<NewVmResponse>,
}

/// Request body for POST /api/vm/{vm_id}/exec/stream/attach
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VmExecStreamAttachRequest {
    /// Optional cursor to resume from (exclusive). If omitted, the full retained backlog is replayed.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "cursor")]
    pub cursor: Option<serde_json::Value>,
    /// Identifier of the exec stream session to reattach to.
    #[serde(rename = "exec_id")]
    pub exec_id: String,
    /// Start streaming after the latest retained chunk (ignores cursor).
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "from_latest")]
    pub from_latest: Option<serde_json::Value>,
}

/// Request body for PATCH /api/vm/{vm_id}/state
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VmUpdateStateRequest {
    /// The requested state for the VM
    #[serde(rename = "state")]
    pub state: VmUpdateStateEnum,
}

/// 
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeleteBaseImageResponse {
    #[serde(rename = "base_image_id")]
    pub base_image_id: String,
    #[serde(rename = "deleted")]
    pub deleted: bool,
}

/// Response body for GET /api/v1/public/repositories
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ListPublicRepositoriesResponse {
    #[serde(rename = "repositories")]
    pub repositories: Vec<PublicRepositoryInfo>,
}

/// Request body for POST /api/v1/commit_tags
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateTagRequest {
    /// The commit ID this tag should point to
    #[serde(rename = "commit_id")]
    pub commit_id: String,
    /// Optional description of what this tag represents
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "description")]
    pub description: Option<serde_json::Value>,
    /// The name of the tag (alphanumeric, hyphens, underscores, dots, 1-64 chars)
    #[serde(rename = "tag_name")]
    pub tag_name: String,
}

/// Response body for GET /api/v1/repositories
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ListRepositoriesResponse {
    /// List of all repositories in the user's organization
    #[serde(rename = "repositories")]
    pub repositories: Vec<RepositoryInfo>,
}

/// Response body for POST /api/v1/repositories/{repo_name}/tags
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateRepoTagResponse {
    /// The commit ID this tag points to
    #[serde(rename = "commit_id")]
    pub commit_id: String,
    /// Full reference in image_name:tag format
    #[serde(rename = "reference")]
    pub reference: String,
    /// The ID of the newly created tag
    #[serde(rename = "tag_id")]
    pub tag_id: String,
}

/// 
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CommitInfo {
    #[serde(rename = "commit_id")]
    pub commit_id: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "description")]
    pub description: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "grandparent_commit_id")]
    pub grandparent_commit_id: Option<serde_json::Value>,
    #[serde(rename = "is_public")]
    pub is_public: bool,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "owner_id")]
    pub owner_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "parent_vm_id")]
    pub parent_vm_id: Option<serde_json::Value>,
}

/// Response body for DELETE /api/v1/domains/{domain_id}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeleteDomainResponse {
    #[serde(rename = "domain_id")]
    pub domain_id: String,
}

/// Repository information returned in list and get operations
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RepositoryInfo {
    /// When the repository was created
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Optional description
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "description")]
    pub description: Option<serde_json::Value>,
    /// Whether this repository is publicly visible
    #[serde(rename = "is_public")]
    pub is_public: bool,
    /// The repository name
    #[serde(rename = "name")]
    pub name: String,
    /// The repository's unique identifier
    #[serde(rename = "repo_id")]
    pub repo_id: String,
}

/// Response body for POST /api/keys/validate
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ValidateKeyResponse {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "valid")]
    pub valid: bool,
}

/// Response body for GET /api/vm/{vm_id}/ssh_key
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VmSshKeyResponse {
    /// The SSH port that will be DNAT'd to the VM's netns (and, in turn, to its TAP device)
    #[serde(rename = "ssh_port")]
    pub ssh_port: i32,
    /// Private SSH key in stringified OpenSSH format
    #[serde(rename = "ssh_private_key")]
    pub ssh_private_key: String,
}

/// The state of a VM
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum VmState {
    #[serde(rename = "booting")]
    Booting,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "paused")]
    Paused,
    #[serde(rename = "sleeping")]
    Sleeping,
    #[serde(rename = "dead")]
    Dead,
}

/// Response body for GET /api/vm/{vm_id}/files
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VmReadFileResponse {
    /// File contents, base64-encoded.
    #[serde(rename = "content_b64")]
    pub content_b64: String,
}

/// Request body for PUT /env_vars — sets (upserts) one or more environment variables.  # Lifecycle model  Environment variables are written to `/etc/environment` inside a VM **once at boot time** via a vsock `WriteFile` request. They are **not** live-synced to running VMs. This is intentional: VMs are ephemeral (create → use → destroy/branch), so env var changes naturally take effect on the next VM.  The `replace` flag exists so callers can atomically express 'I want exactly these variables and nothing else' without having to DELETE each stale key individually. Without it, the only way to remove a variable from future VMs is a separate `DELETE /env_vars/{key}` call per key.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SetEnvVarsRequest {
    /// If true, delete all existing variables before writing the new set. This gives 'set exactly these vars' semantics. Default: false (upsert).
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "replace")]
    pub replace: Option<bool>,
    /// Key-value pairs to set. Keys must be valid shell identifiers (`^[A-Za-z_][A-Za-z0-9_]*$`, max 256 chars). Values max 8192 chars.  When `replace` is false (default): existing keys are overwritten, keys not mentioned are left untouched (upsert semantics).  When `replace` is true: all existing variables are deleted first, then only the provided vars are stored (replace-all semantics).
    #[serde(rename = "vars")]
    pub vars: serde_json::Value,
}

/// The response body for POST /api/vm/{vm_id}/commit
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VmCommitResponse {
    /// The UUID of the newly-created commit
    #[serde(rename = "commit_id")]
    pub commit_id: String,
}

/// Response body for POST /api/v1/repositories/fork
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ForkRepositoryResponse {
    /// The new commit in your org (snapshot of the forked VM)
    #[serde(rename = "commit_id")]
    pub commit_id: String,
    /// Full reference: repo_name:tag_name
    #[serde(rename = "reference")]
    pub reference: String,
    /// The new repository name in your org
    #[serde(rename = "repo_name")]
    pub repo_name: String,
    /// The tag name pointing to the forked commit
    #[serde(rename = "tag_name")]
    pub tag_name: String,
    /// The new VM that was created from the fork
    #[serde(rename = "vm_id")]
    pub vm_id: String,
}

/// 
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ImageSourceRequest {
    ImageRef {
        image_ref: String,
        type: String,
    },
    Bucket {
        bucket: String,
        key: String,
        type: String,
    },
}

/// Possible options for the state requested in PATCH /api/vm/{vm_id}/state
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum VmUpdateStateEnum {
    #[serde(rename = "Paused")]
    Paused,
    #[serde(rename = "Running")]
    Running,
}

/// 
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ErrorResponse {
    /// Reason of error
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "error")]
    pub error: Option<String>,
    /// Is always: false
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "success")]
    pub success: Option<bool>,
}

/// Request body for PATCH /commits/{commit_id}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UpdateCommitRequest {
    /// Optional description for the commit.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "description")]
    pub description: Option<serde_json::Value>,
    #[serde(rename = "is_public")]
    pub is_public: bool,
    /// Optional human-readable name for the commit.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "name")]
    pub name: Option<serde_json::Value>,
}

/// Request body for POST /api/v1/repositories
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateRepositoryRequest {
    /// Optional description of the repository
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "description")]
    pub description: Option<serde_json::Value>,
    /// The name of the repository (alphanumeric, hyphens, underscores, dots, 1-64 chars)
    #[serde(rename = "name")]
    pub name: String,
}

/// Response type for domain operations.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DomainResponse {
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "domain")]
    pub domain: String,
    #[serde(rename = "domain_id")]
    pub domain_id: String,
    #[serde(rename = "vm_id")]
    pub vm_id: String,
}

/// The request body for POST /api/vm/{vm_id}/commit
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VmCommitRequest {
    /// If provided, chelsea will use the requested commit UUID. Otherwise, it will generate a UUID itself.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "commit_id")]
    pub commit_id: Option<serde_json::Value>,
    /// Optional description for the commit.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "description")]
    pub description: Option<serde_json::Value>,
    /// Optional human-readable name for the commit. Defaults to auto-generated name if not provided.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "name")]
    pub name: Option<serde_json::Value>,
}

/// Settings for the deploy build pipeline.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeploySettings {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "build_command")]
    pub build_command: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "install_command")]
    pub install_command: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "run_command")]
    pub run_command: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "working_directory")]
    pub working_directory: Option<serde_json::Value>,
}

/// 
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateBaseImageRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "description")]
    pub description: Option<serde_json::Value>,
    #[serde(rename = "image_name")]
    pub image_name: String,
    /// Additional capacity in MiB beyond the actual filesystem size (defaults to 256). The final image size = calculated rootfs size + this value. Set to 0 for minimum possible image size, or higher for more free space.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "size_mib")]
    pub size_mib: Option<i32>,
    #[serde(rename = "source")]
    pub source: ImageSourceRequest,
}

/// Request body for POST /api/v1/repositories/fork
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ForkRepositoryRequest {
    /// Name for the new repository in your org (defaults to source_repo if omitted)
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "repo_name")]
    pub repo_name: Option<serde_json::Value>,
    /// The organization that owns the source public repository
    #[serde(rename = "source_org")]
    pub source_org: String,
    /// The source repository name
    #[serde(rename = "source_repo")]
    pub source_repo: String,
    /// The tag to fork (e.g. 'latest', 'v1.0')
    #[serde(rename = "source_tag")]
    pub source_tag: String,
    /// Tag name in the new repo (defaults to source_tag if omitted)
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "tag_name")]
    pub tag_name: Option<serde_json::Value>,
}

/// 
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VmCommitEntity {
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "description")]
    pub description: Option<serde_json::Value>,
    /// The commit that this commit's parent VM was started from, if any. Intended to optimize traversing the commit tree.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "grandparent_commit_id")]
    pub grandparent_commit_id: Option<serde_json::Value>,
    #[serde(rename = "id")]
    pub id: String,
    /// Whether this commit is publicly accessible (readable/restorable by anyone).
    #[serde(rename = "is_public")]
    pub is_public: bool,
    #[serde(rename = "name")]
    pub name: String,
    /// api key id.
    #[serde(rename = "owner_id")]
    pub owner_id: String,
    /// The VM that this commit was created from, if any.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "parent_vm_id")]
    pub parent_vm_id: Option<serde_json::Value>,
}

/// Tag information returned in list and get operations
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TagInfo {
    /// The commit ID this tag currently points to
    #[serde(rename = "commit_id")]
    pub commit_id: String,
    /// When the tag was created
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Optional description of what this tag represents
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "description")]
    pub description: Option<serde_json::Value>,
    /// The tag's unique identifier
    #[serde(rename = "tag_id")]
    pub tag_id: String,
    /// The name of the tag
    #[serde(rename = "tag_name")]
    pub tag_name: String,
    /// When the tag was last updated (moved to different commit or description changed)
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

/// Request body for PUT /api/vm/{vm_id}/files
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VmWriteFileRequest {
    /// File contents, base64-encoded.
    #[serde(rename = "content_b64")]
    pub content_b64: String,
    /// Create parent directories if they don't exist.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "create_dirs")]
    pub create_dirs: Option<bool>,
    /// File mode (e.g. 0644). Defaults to 0644 if omitted.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "mode")]
    pub mode: Option<i32>,
    /// Destination path on the VM.
    #[serde(rename = "path")]
    pub path: String,
}

/// Streams available for exec logging.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum VmExecLogStream {
    #[serde(rename = "stdout")]
    Stdout,
    #[serde(rename = "stderr")]
    Stderr,
}

/// Individual log entry describing emitted stdout/stderr chunk.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VmExecLogEntry {
    /// Base64-encoded bytes from stdout/stderr chunk.
    #[serde(rename = "data_b64")]
    pub data_b64: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "exec_id")]
    pub exec_id: Option<serde_json::Value>,
    #[serde(rename = "stream")]
    pub stream: VmExecLogStream,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
}

/// 
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LabelVmRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "labels")]
    pub labels: Option<serde_json::Value>,
}

/// Response for GET /api/v1/vm/{vm_id}/metadata
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VmMetadataResponse {
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "deleted_at")]
    pub deleted_at: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "grandparent_vm_id")]
    pub grandparent_vm_id: Option<serde_json::Value>,
    #[serde(rename = "ip")]
    pub ip: String,
    #[serde(rename = "owner_id")]
    pub owner_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "parent_commit_id")]
    pub parent_commit_id: Option<serde_json::Value>,
    #[serde(rename = "state")]
    pub state: VmState,
    #[serde(rename = "vm_id")]
    pub vm_id: String,
}

/// Request body for PATCH /api/v1/repositories/{repo_name}/visibility
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SetRepositoryVisibilityRequest {
    /// Whether the repository should be publicly visible
    #[serde(rename = "is_public")]
    pub is_public: bool,
}

/// Request body for PATCH /api/v1/repositories/{repo_name}/tags/{tag_name}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UpdateRepoTagRequest {
    /// Optional new commit ID to move the tag to
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "commit_id")]
    pub commit_id: Option<serde_json::Value>,
    /// Optional new description for the tag. Send `null` to clear.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "description")]
    pub description: Option<serde_json::Value>,
}

/// Struct representing configuration options common to all VMs
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VmCreateVmConfig {
    /// The disk size, in MiB.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "fs_size_mib")]
    pub fs_size_mib: Option<serde_json::Value>,
    /// The filesystem base image name. Currently, must be 'default'
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "image_name")]
    pub image_name: Option<serde_json::Value>,
    /// The kernel name. Currently, must be 'default.bin'
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "kernel_name")]
    pub kernel_name: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "labels")]
    pub labels: Option<serde_json::Value>,
    /// The RAM size, in MiB.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "mem_size_mib")]
    pub mem_size_mib: Option<serde_json::Value>,
    /// How many vCPUs to allocate to this VM (and its children)
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "vcpu_count")]
    pub vcpu_count: Option<serde_json::Value>,
}

/// Response body for new VM requests (new_root, from_commit, branch)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NewVmResponse {
    #[serde(rename = "vm_id")]
    pub vm_id: String,
}

/// Request body for POST /api/v1/vm/from_commit
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FromCommitVmRequest {
    CommitId {
        commit_id: String,
    },
    TagName {
        tag_name: String,
    },
    Ref {
        #[serde(rename = "ref")]
        ref_field: String,
    },
}

/// 
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VM {
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "labels")]
    pub labels: Option<serde_json::Value>,
    #[serde(rename = "owner_id")]
    pub owner_id: String,
    #[serde(rename = "state")]
    pub state: VmState,
    #[serde(rename = "vm_id")]
    pub vm_id: String,
}

/// Request body for POST /api/v1/domains
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateDomainRequest {
    #[serde(rename = "domain")]
    pub domain: String,
    #[serde(rename = "vm_id")]
    pub vm_id: String,
}

/// Request body for PATCH /api/v1/commit_tags/{tag_name}  For `description`: - Field absent from JSON → don't change the description - Field present as `null` → clear the description - Field present as `'text'` → set the description to 'text'
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UpdateTagRequest {
    /// Optional new commit ID to move the tag to
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "commit_id")]
    pub commit_id: Option<serde_json::Value>,
    /// Optional new description for the tag. Send `null` to clear an existing description.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "description")]
    pub description: Option<serde_json::Value>,
}

/// 
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UploadBaseImageResponse {
    #[serde(rename = "image_name")]
    pub image_name: String,
    #[serde(rename = "job_id")]
    pub job_id: String,
    #[serde(rename = "status")]
    pub status: String,
}

/// 
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BaseImageStatusResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "error_message")]
    pub error_message: Option<serde_json::Value>,
    #[serde(rename = "image_name")]
    pub image_name: String,
    #[serde(rename = "size_mib")]
    pub size_mib: i32,
    #[serde(rename = "status")]
    pub status: String,
}

/// 
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ListBaseImagesResponse {
    #[serde(rename = "images")]
    pub images: Vec<BaseImageInfo>,
    #[serde(rename = "limit")]
    pub limit: i64,
    #[serde(rename = "offset")]
    pub offset: i64,
    #[serde(rename = "total")]
    pub total: i64,
}

/// 
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NewRootRequest {
    #[serde(rename = "vm_config")]
    pub vm_config: VmCreateVmConfig,
}

/// Request body for PATCH /api/vm/{vm_id}/disk
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VmResizeDiskRequest {
    /// The new disk size in MiB. Must be strictly greater than the current size.
    #[serde(rename = "fs_size_mib")]
    pub fs_size_mib: i32,
}

/// Response body for DELETE /api/vm/{vm_id}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VmDeleteResponse {
    #[serde(rename = "vm_id")]
    pub vm_id: String,
}

/// Response body for POST /api/v1/commit_tags
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateTagResponse {
    /// The commit ID this tag points to
    #[serde(rename = "commit_id")]
    pub commit_id: String,
    /// The ID of the newly created tag
    #[serde(rename = "tag_id")]
    pub tag_id: String,
    /// The name of the tag
    #[serde(rename = "tag_name")]
    pub tag_name: String,
}

/// Request body for `POST /api/v1/deploy`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeployRequest {
    /// Git branch to clone (defaults to repo default branch).
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "branch")]
    pub branch: Option<serde_json::Value>,
    /// Optional project name (defaults to repo name).
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "name")]
    pub name: Option<serde_json::Value>,
    /// GitHub repository in `owner/repo` format.
    #[serde(rename = "repo")]
    pub repo: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "settings")]
    pub settings: Option<serde_json::Value>,
}

/// Tag information within a repository context
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RepoTagInfo {
    /// The commit ID this tag currently points to
    #[serde(rename = "commit_id")]
    pub commit_id: String,
    /// When the tag was created
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Optional description
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "description")]
    pub description: Option<serde_json::Value>,
    /// Full reference in image_name:tag format
    #[serde(rename = "reference")]
    pub reference: String,
    /// The tag's unique identifier
    #[serde(rename = "tag_id")]
    pub tag_id: String,
    /// The tag name
    #[serde(rename = "tag_name")]
    pub tag_name: String,
    /// When the tag was last updated
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

/// Response for exec log tail requests.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VmExecLogResponse {
    /// Returned log entries.
    #[serde(rename = "entries")]
    pub entries: Vec<VmExecLogEntry>,
    /// True when the end of file was reached.
    #[serde(rename = "eof")]
    pub eof: bool,
    /// Next byte offset to continue from.
    #[serde(rename = "next_offset")]
    pub next_offset: i64,
}


// ── Params types for operations with query parameters ───────────────

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ResizeVmDiskParams {
    /// If true, return an error immediately if the VM is still booting. Default: false
    pub skip_wait_boot: Option<bool>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreateNewRootVmParams {
    /// If true, wait for the newly-created VM to finish booting before returning. Default: false.
    pub wait_boot: Option<bool>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct VmLogsParams {
    /// Byte offset into the log file (default: 0)
    pub offset: Option<i64>,
    /// Maximum number of log entries to return
    pub max_entries: Option<i64>,
    /// Filter by 'stdout' or 'stderr'
    pub stream: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct BranchByRefParams {
    /// Number of VMs to branch (optional; default 1)
    pub count: Option<i64>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct BranchByTagParams {
    /// Number of VMs to branch (optional; default 1)
    pub count: Option<i64>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct BranchVmParams {
    /// If true, keep VM paused after commit. Only applicable when branching a VM ID.
    pub keep_paused: Option<bool>,
    /// If true, immediately return an error if VM is booting instead of waiting. Only applicable when branching a VM ID.
    pub skip_wait_boot: Option<bool>,
    /// Number of VMs to branch (optional; default 1)
    pub count: Option<i64>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UpdateVmStateParams {
    /// If true, error immediately if the VM is not finished booting. Defaults to false
    pub skip_wait_boot: Option<bool>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DeleteVmParams {
    /// If true, return an error immediately if the VM is still booting. Default: false
    pub skip_wait_boot: Option<bool>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct BranchByVmParams {
    /// If true, keep VM paused after commit
    pub keep_paused: Option<bool>,
    /// If true, immediately return an error if VM is booting instead of waiting
    pub skip_wait_boot: Option<bool>,
    /// Number of VMs to branch (optional; default 1)
    pub count: Option<i64>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CommitVmParams {
    /// If true, keep VM paused after commit
    pub keep_paused: Option<bool>,
    /// If true, return an error immediately if the VM is still booting. Default: false
    pub skip_wait_boot: Option<bool>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListDomainsParams {
    /// Filter by VM ID
    pub vm_id: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ReadFileVmParams {
    /// Absolute path of the file to read
    pub path: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct BranchByCommitParams {
    /// Number of VMs to branch (optional; default 1)
    pub count: Option<i64>,
}

